# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'DMT' do
  # Comment the next line if you're not using Swift and don't want to use #dynamic frameworks
  use_frameworks!

  pod 'SwiftEvents', '~> 1.1.1'
  pod 'Zip', '~> 1.1'
  pod 'Toast-Swift', '~> 5.0.1'
end
